### ISSUE TITLE
Update pinned version of grype to 0.1.0

### ISSUE THREAD

**Issue by luhring** [anchore/grype-vscode#34]
Once the final `0.1.0` release of grype is available, update the pin to point to this release (in `src/config.ts`).

**Comment by zhill** [comment]
Should we support a range using semver instead? e.g. ~0.1.0

**Comment by luhring** [comment]
@zhill That makes sense. There's already logic that can fetch a release from GitHub and leverage checksums to guarantee the correct binary has been procured for the integration. We'd just need to update that logic to search for releases within the intended semver range, specifically in these files:

- https://github.com/anchore/grype-vscode/blob/main/src/executable/ExecutableProvider.ts
- https://github.com/anchore/grype-vscode/blob/main/src/executable/Verifier.ts
